name: Scrape and Update

on:
  push:
    branches:
      - master

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
         
      - name: Run script
        run: python booking_scraper2.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hotels_list2
          path: hotels_list2.csv
          overwrite: true
          retention-days: 5
    
